DROP TABLE IF EXISTS Io.TaggedNote;
DROP TABLE IF EXISTS Io.Tag;
DROP TABLE IF EXISTS Io.LoggedReminder;
DROP TABLE IF EXISTS Io.Reminder;
DROP TABLE IF EXISTS Io.Note;
DROP TABLE IF EXISTS Io.Permission;
DROP TABLE IF EXISTS Io.Folder;
DROP TABLE IF EXISTS Sifrarnik.GroupUser;
DROP TABLE IF EXISTS Sifrarnik."User";
DROP TABLE IF EXISTS Sifrarnik."Group";
DROP TABLE IF EXISTS Sifrarnik.Organisation;

DROP SCHEMA IF EXISTS Io;
DROP SCHEMA IF EXISTS Sifrarnik;
